# Database Configuration (H2 In-Memory)
spring.datasource.url=jdbc:h2:mem:sharebitedb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# Enable H2 Web Console for local database inspection
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
# Allow frame loading so H2 console works in browser
spring.headers.frame-options=sameorigin

# Hibernate Settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Server configuration
server.port=8080

# JWT Settings (Secret key must be at least 256 bits)
sharebite.jwt.secret=9a67a8698c9f56360c70d741d40dc780d6b5e52c803889158bc2831e505a4155
sharebite.jwt.expiration=86400000
